### PR TITLE
Intergrate with openlab ci for testing

### PR DESCRIPTION
**Pull request by liu-sheng**

### CODE REVIEW

**Comment by liu-sheng** [comment]
recheck telefonica

**Comment by animationzl** [comment]
LGTM

**Comment by kiwik** [comment]
.zuul.yaml looks good to me, but telefornica zuul-jobs should be updated, actually the only one test case is skipped now. https://github.com/theopenlab/openlab-zuul-jobs/blob/master/playbooks/terraform-provider-telefonicaopencloud-acceptance-test/run.yaml#L44

**Comment by liu-sheng** [comment]
recheck telefonica

**Pull request merged**
